name: 'Preview Pull Requests in Google Kubernetes Service'
description: 'A Github Action to deploy moleculer app preview of Pull Requests to GKE - Google Kubernetes Engine using Moleculer Helm charts 🚀'
author: 'Mahmoud Almasri'
inputs:
 command:
    required: true
    default: "deploy"
    description: "Command to run"

runs:
  using: "composite"
  steps:
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ inputs.GCR_JSON_KEY }}

branding:
  icon: 'check-circle'  
  color: 'orange'